AllCops:
  Exclude:
    - 'bin/*'
    - 'spec/dummy/bin/*'
    - 'spec/dummy/db/**/*'
    - 'db/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
   Enabled: false
